apiVersion: v1
kind: Service
metadata:
  name: wil-playground
  labels:
    app: wil-playground
spec:
  type: NodePort
  ports:
  - name: 8888
    nodePort: 8888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: wil-playground
